/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.typingtanuki.mail;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;
import java.util.stream.Collectors;

public class MailReader {
    public static void main(String[] args) {
        if (args.length != 1) {
            System.err.println("Only 1 argument: The folder with the mbox files");
            System.exit(10);
        }
        CharExtractor extractor = new CharExtractor(12);
        Path root = Paths.get(args[0]);
        try {
            List<Path> paths = Files
                    .list(root)
                    .filter(path -> !path.getFileName().toString().contains(".")).collect(Collectors.toList());


            for (Path path : paths) {
                List<String> extractedContent = MboxReader.read(path);
                extractor.process(extractedContent);
            }

            extractor.display();
        } catch (IOException e) {
            System.err.println("Error listing mailboxes");
            e.printStackTrace(System.err);
            System.exit(11);
        }
    }
}
